"""
Research Output Persistence
Owner: Knowledge Officer
Date: 2026-06-13
Purpose: Standard for persisting research findings to knowledge/research/.
         Ensures research outputs are reusable and retrievable.

Standard format:
    knowledge/research/RESEARCH-{YYYYMMDD-HHMMSS}-{slug}.md

Public API:
    save_research_output(topic, summary, sources, mission_id, findings) -> Path | None
    load_recent_research(topic_keywords, limit) -> list[dict]
    format_research_notice(path) -> str
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Optional


_REPO_ROOT = Path(__file__).resolve().parents[1]
_RESEARCH_DIR = _REPO_ROOT / "knowledge" / "research"
_TEXT_SUFFIXES = {".md", ".txt"}


def _make_slug(text: str) -> str:
    cleaned = re.sub(r"[^a-z0-9 ]", "", text.strip().lower())
    words = cleaned.split()[:5]
    return "-".join(words) or "research"


def save_research_output(
    topic: str,
    summary: str,
    sources: list[str] | None = None,
    mission_id: str | None = None,
    findings: list[str] | None = None,
    tags: list[str] | None = None,
) -> Optional[Path]:
    """Save a research output to knowledge/research/. Returns the saved path or None on failure."""
    try:
        _RESEARCH_DIR.mkdir(parents=True, exist_ok=True)
    except OSError:
        return None

    now = datetime.now()
    slug = _make_slug(topic)
    filename = f"RESEARCH-{now.strftime('%Y%m%d-%H%M%S')}-{slug}.md"
    path = _RESEARCH_DIR / filename

    lines = [
        f"# Research Output: {topic}",
        "",
        "## Metadata",
        "",
        f"- Date: {now.strftime('%Y-%m-%d %H:%M')}",
        f"- Mission: {mission_id or 'N/A'}",
        f"- Tags: {', '.join(tags or [])}",
        "",
        "## Summary",
        "",
        summary.strip(),
        "",
    ]

    if findings:
        lines += ["## Key Findings", ""]
        for finding in findings:
            lines.append(f"- {finding.strip()}")
        lines.append("")

    if sources:
        lines += ["## Sources", ""]
        for source in sources:
            lines.append(f"- {source.strip()}")
        lines.append("")

    lines += [
        "## Retrieval Guidance",
        "",
        f"Query via Slack: `what do we know about {topic[:40]}`",
        "",
        "---",
        "",
        "*Generated by Starship Endeavour research pipeline.*",
    ]

    try:
        path.write_text("\n".join(lines), encoding="utf-8")
        return path
    except OSError:
        return None


def load_recent_research(topic_keywords: list[str], limit: int = 5) -> list[dict]:
    """Return recent research records that match any of the topic keywords.

    Each result: {"title": str, "date": str, "path": str, "summary_lines": list[str]}
    """
    if not _RESEARCH_DIR.exists():
        return []

    keyword_set = {k.lower() for k in topic_keywords}
    matches: list[dict] = []

    for path in sorted(_RESEARCH_DIR.glob("RESEARCH-*.md"), reverse=True):
        try:
            content = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue

        content_lower = content.lower()
        if not any(kw in content_lower for kw in keyword_set):
            continue

        # Extract title and summary
        title_match = re.search(r"^# Research Output:\s*(.+)$", content, re.MULTILINE)
        title = title_match.group(1).strip() if title_match else path.stem

        date_match = re.search(r"- Date:\s*(.+)$", content, re.MULTILINE)
        date_str = date_match.group(1).strip() if date_match else "unknown"

        summary_match = re.search(r"## Summary\s*\n+(.+?)(?=\n##|\Z)", content, re.DOTALL)
        summary_lines = []
        if summary_match:
            summary_lines = [
                line.strip() for line in summary_match.group(1).strip().splitlines()
                if line.strip()
            ][:3]

        matches.append({
            "title": title,
            "date": date_str,
            "path": str(path.relative_to(_REPO_ROOT)),
            "summary_lines": summary_lines,
        })

        if len(matches) >= limit:
            break

    return matches


def format_research_notice(path: Path) -> str:
    """Return a Slack notice confirming research was saved."""
    try:
        rel = path.relative_to(_REPO_ROOT)
    except ValueError:
        rel = path
    return f":floppy_disk: Research output saved to `{rel}` — retrievable via knowledge queries."


def surface_prior_research(topic: str) -> str:
    """Return a formatted summary of prior research on a topic, for surfacing at query time."""
    keywords = re.sub(r"[^a-z0-9 ]", " ", topic.lower()).split()
    keywords = [w for w in keywords if len(w) > 3]
    if not keywords:
        return ""

    records = load_recent_research(keywords, limit=3)
    if not records:
        return ""

    lines = [":satellite: *Prior research on this topic:*"]
    for r in records:
        lines.append(f"  • `{r['path']}` ({r['date']}) — {r['title']}")
        if r["summary_lines"]:
            lines.append(f"    _{r['summary_lines'][0]}_")
    return "\n".join(lines)
